### ISSUE TITLE
Support for enum in map

### ISSUE THREAD

**Issue by ebussieres** [mbosecke/pebble#114]
It would be nice to support enum in GetAttributeExpression when keys of a map are enum. For example : 

```javascript
{{ myMap.get('ENUM_ENTRY') }}
```

would return the entry of the map

**Comment by thomashunziker** [comment]
I was missing also some sort of Enum access. However it is dangerous to have arbitrary access to enums, because enums can have methods and if you are able to access any enum you are eventually able to harm the application from inside a template. Eventually we should add some way to register those enums which can be accessed via templates.

**Comment by thomashunziker** [comment]
I add support for using equal with enums (see #120).

**Comment by mbosecke** [comment]
That's a very interesting security concern that @thomashunziker brings up. To be able to access enums that exist on the classpath would mean that the template is capable of extending it's reach beyond just the variables that are provided during the evaluation phase. 

I think because of these security concerns, this functionality should probably exist in a third party extension. In theory you can create a custom "enum" function that accepts a string as an argument and searches the classpath for a matching enum to return.
