### ISSUE TITLE
How about introducing a default template strategy?

### ISSUE THREAD

**Issue by donnior** [mbosecke/pebble#145]
Now if we have dozens of of pages which every one need inherit from one template layout, we need to write  `{% extends "parent.html" %}` in every single page.

Can we introducing a default template layout resolve strategy? Then we can ignore the duplicated `extends` in those page need inherit from it. For those don't need inherit from default page, we can still use `extends 'xxxx'` or `extends null` to specify one parent page or don't use inheritance.

**Comment by mbosecke** [comment]
My first thought is that this functionality is better suited for whatever text editor you use to write your templates. Most editors/IDEs have a "macro" feature which allow you to inject commonly written text.

My concern is that it significantly reduces the readability of the individual template and the *only* benefit is that it saves ~30 keystrokes (or a single copy/paste). 

If the developer writing the child template doesn't know that there's a default parent template, it becomes much more likely for the developer to accidentally override a parent block just because they happened to use the same block name.

**Comment by donnior** [comment]
Yeah I agree with you @mbosecke , my thought comes out because some framework (like RoR) support this. Now I know your concern and will close this issue.
