### ISSUE TITLE
Pebble 2.0.0 breaks on GAE/J

### ISSUE THREAD

**Issue by sgammon** [mbosecke/pebble#151]
Hey Pebble devs!

First of all, we love Pebble. We fell in love with Jinja in Python, too. We're using Pebble on Google App Engine, and in the recent upgrade to `2.0.0`, we began encountering the following exception:

```
java.lang.NoClassDefFoundError: java.util.ResourceBundle$Control is a restricted class. Please see the Google  App Engine developer's guide for more details.
	at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:52)
	at com.mitchellbosecke.pebble.extension.i18n.UTF8Control.<init>(UTF8Control.java:12)
	at com.mitchellbosecke.pebble.extension.i18n.i18nFunction.<init>(i18nFunction.java:21)
	at com.mitchellbosecke.pebble.extension.i18n.I18nExtension.getFunctions(I18nExtension.java:22)
	at com.mitchellbosecke.pebble.extension.ExtensionRegistry.<init>(ExtensionRegistry.java:108)
	at com.mitchellbosecke.pebble.PebbleEngine.<init>(PebbleEngine.java:89)
	at com.mitchellbosecke.pebble.PebbleEngine.<init>(PebbleEngine.java:52)
	at com.mitchellbosecke.pebble.PebbleEngine$Builder.build(PebbleEngine.java:469)
```

It seems that the class `ResourceBundle.Control` is not whitelisted in GAE's Java runtime. Tracing the exception, it looks like Pebble's `i18n` extension (which is added by default) makes use of this class.

Unfortunately, I also don't see an easy way of replacing the default extensions (we don't use `i18n` and could safely live without it, unless it's doing something magic and critical behind the scenes):

1) Mutating the internal default extension state for `Builder` is not an option, as no setter is provided (only an adder, of 'user-provided' extensions) and the internal array is marked `private`
2) Extending the nested `PebbleEngine.Builder` class and overriding `build()` gets you nowhere, as most variables on `Builder` are `private` and without getters, so you'd basically have to rewrite it anyway
3) Rewriting the `Builder` class doesn't work because `PebbleEngine`'s initializer is also `private`, which would preclude #2 as well anyways

Perhaps there is a way to disable using the default extensions in `PebbleEngine.Builder.build()`, and I am mistaken... let me know if that is the case and I will quietly close this issue :).

If that isn't the case, I'm happy to submit a pull, but I'm wondering which approach the Pebble community would prefer:

1) Adding a method to `Builder` called `setDefaultExtensions`, along with getters while we're at it so we can avoid future issues like these (this seems like the least invasive approach)
2) Adding getters to `Builder` and marking `PebbleEngine`'s initializer as `protected`. If you'd like to use your own set of default extensions, overriding `build()` in `PebbleEngine.Builder` is all you need to do.

~~I'm already working on approach 1 in a pull locally and I'm happy to share my code if anybody else is experiencing this issue.~~ Pull filed at mbosecke/pebble#152 with a much simpler approach.

**Comment by stickfigure** [comment]
We haven't upgraded to 2.0 yet but this will definitely affect us on GAE - thanks for the heads up!

**Comment by sgammon** [comment]
(@stickfigure! I recognize that profile pic :grinning:. Thanks for Objectify, it's an awesome library that we love using in tandem with Pebble.)

Here's my patched version of Pebble that I'm using quite smoothly in production on GAE, in case it is useful to you. It's not mainline, but I haven't heard much back on #152.
[pebble-2-0-2-SNAPSHOT.jar.gz](https://github.com/mbosecke/pebble/files/92394/pebble-2-0-2-SNAPSHOT.jar.gz)

**Comment by mbosecke** [comment]
Sorry for the delay in responding.

I left a comment on the #152 request explaining why I'm not a fan of those changes. Although, I'm still unsure of how to continue with this task. Ideally I would like to alter the i18n extension so that it just works on GAE.

**Comment by sgammon** [comment]
No worries @mbosecke, thanks for your response. Unfortunately I think adapting i18n to GAE is outside the scope of my skill. We don't use the i18n extension currently but if you need a tester I'm happy to help.

**Comment by mbosecke** [comment]
I just committed 7014511 which might be a small work around for the time being. It's a very small change; basically the culprit class is no longer constructed when the i18n extension is registered, it is lazy and only constructed when the i18n extension is actually invoked. It's not perfect because:
* It is a performance hit for anyone using the i18n extension.
* No one can actually use the i18n extension in GAE

But I think it's a sacrifice I'm willing to take at this time and I can revisit the above problems when they come up. 

Are you able to test if this fixes the problem?

**Comment by stickfigure** [comment]
I just tested it in the GAE dev environment (which checks the classpath) and it worked great. 

Looking at ResourceBundle.Control, it doesn't appear to do anything in the constructor and has no member data, so it's just an empty object instance creation - shouldn't have much performance impact (at least not compared to all the other garbage generated during rendering). Looks like a fine solution to me!

I opened this issue in the GAE issue tracker, but since this is security related I wouldn't expect it to be addressed quickly:  https://code.google.com/p/googleappengine/issues/detail?id=12691

Thanks @mbosecke and @sgammon! I've used pretty much every template system ever written for the JVM, and Pebble is the first one that makes me really happy :)

**Comment by mbosecke** [comment]
Thanks @stickfigure! I really appreciate it. 

I'll also be keeping my eyes on the GAE issue.

**Comment by JesseTG** [comment]
So, to clarify, I *can* use this on Google App Engine now?

**Comment by stickfigure** [comment]
2.1.0 is working for me in production yep!

**Comment by Arosner** [comment]
I'm having the same issue with version 2.2.0 with the GAE dev server. It seems to stem from the registration of the utf-8 extension.

**Comment by mbosecke** [comment]
Are you actually trying to use the extension? Because yes, using it will probably fail and in my opinion this is the fault of GAE. If you're not using the extension and pebble is still failing, let me know.

**Comment by Arosner** [comment]
No I am not trying to use the extension.
