### ISSUE TITLE
2.0.0 Global variables?

### ISSUE THREAD

**Issue by realcnbs** [mbosecke/pebble#153]
Looks like 2.0 breaks the functionality when you could set some vars in an included file and use them in other files.

**Comment by Quantum64** [comment]
I can confirm this.

**Comment by realcnbs** [comment]
@mbosecke is it a feature or a bug? 
This issue basically a show stopper for us, we can't upgrade because that would require rethinking/redoing/testing lots of templates we already have.

**Comment by mbosecke** [comment]
There was a discussion in #121 that changed the default behavior of the "include" tag to isolate the included template; the variables of the included template are now within their own scope and do not affect the variables of the template that included it. So yes, this was by design.

What's your use case for wanting an included template to be able to affect variables within the current template? 

I still think it's a good idea to have included templates isolated by default but I'm open to ideas on how a user may be able to explicitly opt-out of that isolation.

**Comment by realcnbs** [comment]
Well, the main user case is that we create a settings file where are some global setting vars are defined and used everywhere else.
But i guess we will have to redo our templates.
