### ISSUE TITLE
JBoss: Loaders can't find templates

### ISSUE THREAD

**Issue by marthjod** [mbosecke/pebble#54]
Pebble's default Loaders are unable to find my template files (I've tried {Delegating,Classpath,File}Loader). Loaders throw a "Could not find template..." exception, even if provided with the real path on the JBoss virtual filesystem (ServletContext.getRealPath()). I've checked that the files are there. Also, if I let my app itself find and read in the template contents, StringLoader works and the template is rendered/displayed. However, this way, I'm unable to use template inheritance because, e.g., Pebble in turn cannot find the appropriate base template.
Somewhat related: issue #2 (JBoss not exploding WAR in-place, but using VFS per deployment).

In general, I'm excited about Pebble because of its Django-like convenience. However, I'm pretty much bound to using JBoss and would be grateful if both worked together.

Are there any known workarounds/experiences with JBoss deployment? Otherwise, I suspect that implementing a "JBossVFSLoader" (adjusting paths under the hood) would be the way to remedy the situation?

**Comment by mbosecke** [comment]
Thanks for bringing this to my attention. Yeah task #2 is pretty much the identical problem but the code base for pebble has changed so dramatically since then that it was solved in a way that is no longer applicable to now.

This is a problem that definitely needs to be resolved; unfortunately I'm very unfamiliar with jboss. I'll have to do some research and in the meantime I'm open to suggestions.

**Comment by mbosecke** [comment]
I added a new ServletLoader which seems to work for me using Wildfly. The loader itself uses "[servletContext#getResourceAsStream](http://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html#getResourceAsStream(java.lang.String))"
