### ISSUE TITLE
Searching for Thymeleaf replacement, some questions.

### ISSUE THREAD

**Issue by Rouche** [mbosecke/pebble#73]
Hi, im am directly coming from Thymeleaf.

Im surprised about the speed of the benchmarks. ill try to create very complex one just to see but its promising, especially if i back it with Spring and JSON/REST

After reading doc i have a couple of questions about features that i don't know how i would replace, or maybe just not documented yet:
-Preprocessor __${}__ in Thymeleaf.

-Change the EL expression language for Spring EL to be able to call static methods e.g.: T(my.Class).PROP, i guess this one could be done with a function taking parameters but we would need Reflect package. And some sort of custom cache.

-Have access to Spring managed beans without adding them to the map. 

Automatic binding and validation processing might not be an issue since i would use Pebble for JSON request through Angular JS anyway.

I might have time soon to contribute some implementations if you want that wont affect the code base. Ill just use pull requests.

Thanks a lot.

**Comment by hectorlf** [comment]
I also come from a Thymeleaf background, so I'll make an attempt to answer with my limited knowledge of both:

- Preprocessing expressions, as Thymeleaf implements them, are not supported and would be hard to implement. Any concrete use case you are targeting with preprocessors?
- Pebble does not use ognl, switching to Spring EL would require a major rewrite. AFAIK, Pebble can already use static fields/methods through object instances, and it would be easy to implement some sort of ".class accessor function" to plug into.
- It would be easy to create an extension to give access to specific Spring beans. If you are using Spring Security objects directly in your thymeleafs, for example, it'd be best to take that functionality into an extension (like Spring Sec. JSP tags).
- AFAIK, there's no binding and validation in the SpringMVC -> Thymeleaf -> Browser chain, but correct me because I may be utterly wrong.

I may advise to see Pebble as a nicer and fun new JSP, rather than a more performant new Thymeleaf.

**Comment by Rouche** [comment]
Hi again. Thanks for answer.

In fact for the preprocessor, i guess we could have implemented it differently.

#1 : We have 5 different beans that implement an interface. The UI is the same but different code behind. We access the methods by first asking a root bean the name of the support bean. like __${root.myImplementationBean}__
Thinking about it we could have just used the same name everywhere and add it manually in the ModelAndView instance. Oh well.

Also, for Thymeleaf to bind properties inside lists. Using th:each="myVar,rowStat : myArray , We get the index like : myArray[__${rowStat.index}__], so all the objects are binded.

Of course all this can be replaced with a UI side binding using AngularJS and JSON request instead. But we were in a special case where client did not want to.

#4 : Thymeleaf's th:object on a form automatically bind the form with properties with the "star" EL accessor *{myPropertyOfThObject}. Like mentionned above, lists are also supported wich is very cool. Validation is done automatically with the @Valid but i guess this is spring integration of JSR . We used the @InitBinder of the controller to set the validator for multiple fields.

In facts all my questions are linked together : Whats the best way, in pebble, to do view / server data communication. Form and fields and validations.

Thanks a lot.

**Comment by hectorlf** [comment]
Almost forgot this, sorry :-/

Not sure how I'd handle validations, but form binding must be coded specifically, either as an extension or as a more JSP approach (you know, writing html input tags with dynamically computed values).

For the implementor beans, the simplest solution I can think of is the one you propose.

**Comment by mbosecke** [comment]
I have such a small amount of experience with Thymeleaf that I unfortunately don't have anything to contribute to this conversation that @hectorlf didn't already mention. Hopefully you were able to get some valuable information, otherwise we can re-open this issue.

**Comment by Rouche** [comment]
I got my answers. I will use Pebble in a different way that Thymeleaf.

Thanks.,


[image: ResoluTech]
*Jean-Francois Larouche*
Architecture de Solutions TI
[image: Cell] 514-965-9224 | [image: Email] contact@resolutech.com
http://www.resolutech.com
<http://ca.linkedin.com/pub/jean-francois-larouche/1/b84/530>
