### ISSUE TITLE
Calling Methods with non string parameter?

### ISSUE THREAD

**Issue by Skerberus** [mbosecke/pebble#95]
Afaik it is currently not possible to call a method that looks like this:
public void getAccounts(boolean removeZeroBalance)...
right? As a workaround I currently have to change the method parameter to String and parse it back to boolean inside the method. Is this the only way or is there a way to call methods that have non String parameter?

**Comment by mbosecke** [comment]
Calling methods with boolean arguments should be possible. Make sure you're using the latest version, v1.6.0, because I fixed some issues regarding primitive arguments. Let me know if you still encounter the issue.

**Comment by mbosecke** [comment]
Closing old issue

**Comment by bjansen** [comment]
I know this is an "old" issue, but I have the same kind of problems. My method is using a `Boolean` (not `boolean`), and it's never called because it looks like `boolean`s are not widened in [this code]( https://github.com/mbosecke/pebble/blob/master/src/main/java/com/mitchellbosecke/pebble/node/expression/GetAttributeExpression.java#L341). Is it an oversight?

**Comment by mbosecke** [comment]
Yup, it might be an oversight, I'll take a look.

**Comment by bjansen** [comment]
I tried adding `boolean` to `widen()`, and everything worked as expected. It might have other side effects, though.

**Comment by mbosecke** [comment]
As long as all of our existing unit tests still pass, we should be good. Want to add a quick unit test for your change and submit a PR?

**Comment by bjansen** [comment]
OK, I'll give it a try then.

**Comment by bjansen** [comment]
https://github.com/mbosecke/pebble/pull/177
